tokens:
  azure:
    type: azure

keys:
  azure:
    token: azure
    id: https://voxelledesktop.vault.azure.net/keys/VoxelleDesktop/3659c31f8f25416d96e64c8d221617bb
    certificate: https://voxelledesktop.vault.azure.net/certificates/VoxelleDesktop/8cdeecbfedfe477eaf854d2774fc9bd5
