/**
 * Generators pane: shared radius/kind + per-generator hooks, and a single object for `GeneratorToolOptions`.
 */

import { useState } from "react";
import { useLatestRef } from "./useLatestRef";
import { useRocksGenerator } from "./useRocksGenerator";
import { useGrassGenerator } from "./useGrassGenerator";
import { useAshlarGenerator } from "./useAshlarGenerator";
import { useFloraGenerator } from "./useFloraGenerator";
import { useRopeClothGenerator } from "./useRopeClothGenerator";
import { useRoofGenerator } from "./useRoofGenerator";
import { useShapeGenerator } from "./useShapeGenerator";
import type { GeneratorKindId } from "../types";
import type { GeneratorToolOptionsModel } from "../toolOptions/GeneratorToolOptions";

export interface GeneratorToolContext {
  activeColorRef: React.MutableRefObject<number>;
  activeMaterialRef: React.MutableRefObject<string>;
  selectionStrokeSnapToSurfaceRef: React.MutableRefObject<boolean>;
  mirrorXRef: React.MutableRefObject<boolean>;
  mirrorYRef: React.MutableRefObject<boolean>;
  mirrorZRef: React.MutableRefObject<boolean>;
}

/** Return type: generator hooks output + tool-options model + kind/radius. */
export function useGeneratorToolState(ctx: GeneratorToolContext) {
  const {
    activeColorRef,
    activeMaterialRef,
    selectionStrokeSnapToSurfaceRef,
    mirrorXRef,
    mirrorYRef,
    mirrorZRef,
  } = ctx;

  const [generatorSphereRadius, setGeneratorSphereRadius] = useState(4);
  const [generatorKind, setGeneratorKind] = useState<GeneratorKindId>("rocks");
  const generatorSphereRadiusRef = useLatestRef(generatorSphereRadius);
  const generatorKindRef = useLatestRef(generatorKind);

  const _genCtx = {
    activeColorRef,
    activeMaterialRef,
    generatorSphereRadiusRef,
    mirrorXRef,
    mirrorYRef,
    mirrorZRef,
  };
  const rocks = useRocksGenerator(_genCtx);
  const {
    rocksAutoCommitOnMouseUp,
    setRocksAutoCommitOnMouseUp,
    rocksAutoCommitOnMouseUpRef,
    rockRoughness,
    setRockRoughness,
    rockRoughnessRef,
    rockCount,
    setRockCount,
    rockCountRef,
    rockClusterRadius,
    setRockClusterRadius,
    rockClusterRadiusRef,
    rockSinkDirection,
    setRockSinkDirection,
    rockSinkDirectionRef,
    rockSinkAmount,
    setRockSinkAmount,
    rockSinkAmountRef,
    rockPreviewSeedRef,
    placeRocksAtScreen,
    rocksPhase,
  } = rocks;

  const grass = useGrassGenerator(_genCtx);
  const {
    grassAutoCommitOnMouseUp,
    setGrassAutoCommitOnMouseUp,
    grassAutoCommitOnMouseUpRef,
    grassDensity,
    setGrassDensity,
    grassDensityRef,
    grassMaxHeight,
    setGrassMaxHeight,
    grassMaxHeightRef,
    grassPreviewSeedRef,
    placeGrassAtScreen,
    grassPhase,
  } = grass;

  const ashlar = useAshlarGenerator({ ..._genCtx, rockRoughnessRef });
  const {
    ashlarAutoCommitOnMouseUp,
    setAshlarAutoCommitOnMouseUp,
    ashlarAutoCommitOnMouseUpRef,
    ashlarThickness,
    setAshlarThickness,
    ashlarThicknessRef,
    ashlarPreviewSeedRef,
    placeAshlarAtScreen,
    ashlarPhase,
  } = ashlar;

  const flora = useFloraGenerator({
    activeColorRef,
    activeMaterialRef,
    mirrorXRef,
    mirrorYRef,
    mirrorZRef,
  });
  const {
    floraAutoCommitOnMouseUp,
    setFloraAutoCommitOnMouseUp,
    floraAutoCommitOnMouseUpRef,
    floraPreset,
    setFloraPreset,
    floraHeight,
    setFloraHeight,
    floraGirth,
    setFloraGirth,
    floraWobble,
    setFloraWobble,
    floraTaper,
    setFloraTaper,
    floraStemCount,
    setFloraStemCount,
    floraClusterRadius,
    setFloraClusterRadius,
    floraBranchCount,
    setFloraBranchCount,
    floraBranchDepth,
    setFloraBranchDepth,
    floraBranchStart,
    setFloraBranchStart,
    floraBranchSpread,
    setFloraBranchSpread,
    floraBraidStrands,
    setFloraBraidStrands,
    floraBraidTwist,
    setFloraBraidTwist,
    floraCanopy,
    setFloraCanopy,
    floraPreviewSeedRef,
    placeFloraAtScreen,
    floraPhase,
  } = flora;

  const ropeCloth = useRopeClothGenerator({
    activeColorRef,
    activeMaterialRef,
    selectionStrokeSnapToSurfaceRef,
    mirrorXRef,
    mirrorYRef,
    mirrorZRef,
  });
  const {
    clothGravityDirection,
    setClothGravityDirection,
    clothGravityDirectionRef,
    ropeBrushRadiusIndex,
    setRopeBrushRadiusIndex,
    ropeBrushRadiusIndexRef,
    ropeBrushShapeUi,
    setRopeBrushShapeUi,
    ropeBrushShapeUiRef,
    ropeFirstScreen,
    setRopeFirstScreen,
    setRopeFirstVoxel,
    ropeFirstVoxelRef,
    ropeSag,
    ropeTension,
    setRopeTension,
    ropeTensionRef,
    ropePhase,
    clothPins,
    setClothPins,
    clothPinsRef,
    clothTension,
    setClothTension,
    clothTensionRef,
    clothSimGravityPct,
    setClothSimGravityPct,
    clothSimGravityPctRef,
    clothSimStiffnessPct,
    setClothSimStiffnessPct,
    clothSimStiffnessPctRef,
    clothSimIterations,
    setClothSimIterations,
    clothSimIterationsRef,
    clothSimConstraintPasses,
    setClothSimConstraintPasses,
    clothSimConstraintPassesRef,
    clothPhase,
    handleClothPinClick,
  } = ropeCloth;

  const roof = useRoofGenerator();
  const {
    roofStyle,
    setRoofStyle,
    roofStyleRef,
    roofHeight,
    setRoofHeight,
    roofHeightRef,
    roofHollow,
    setRoofHollow,
    roofHollowRef,
    roofPins,
    setRoofPins,
    roofPinsRef,
    roofAreaShape,
    setRoofAreaShape,
    roofAreaShapeRef,
    roofFirstClick,
    setRoofFirstClick,
    roofFirstClickRef,
  } = roof;

  const shape = useShapeGenerator({
    activeColorRef,
    activeMaterialRef,
    mirrorXRef,
    mirrorYRef,
    mirrorZRef,
  });
  const {
    shapeKind,
    setShapeKind,
    shapeKindRef,
    shapeSize,
    setShapeSize,
    shapeSizeRef,
    shapeRotX,
    setShapeRotX,
    shapeRotXRef,
    shapeRotY,
    setShapeRotY,
    shapeRotYRef,
    shapeRotZ,
    setShapeRotZ,
    shapeRotZRef,
    shapeOverwrite,
    setShapeOverwrite,
    shapeOverwriteRef,
    shapePhase,
    shapeGizmoPosRef,
  } = shape;

  const generatorToolOptionsModel: GeneratorToolOptionsModel = {
    generatorKind,
    generatorSphereRadius,
    setGeneratorSphereRadius,
    rocksAutoCommitOnMouseUp,
    setRocksAutoCommitOnMouseUp,
    rockRoughness,
    setRockRoughness,
    rockCount,
    setRockCount,
    rockClusterRadius,
    setRockClusterRadius,
    rockSinkDirection,
    setRockSinkDirection,
    rockSinkAmount,
    setRockSinkAmount,
    grassDensity,
    setGrassDensity,
    grassMaxHeight,
    setGrassMaxHeight,
    grassAutoCommitOnMouseUp,
    setGrassAutoCommitOnMouseUp,
    clothGravityDirection,
    setClothGravityDirection,
    ropeBrushShapeUi,
    setRopeBrushShapeUi,
    ropeBrushRadiusIndex,
    setRopeBrushRadiusIndex,
    clothSimGravityPct,
    setClothSimGravityPct,
    clothSimStiffnessPct,
    setClothSimStiffnessPct,
    clothSimIterations,
    setClothSimIterations,
    clothSimConstraintPasses,
    setClothSimConstraintPasses,
    ashlarThickness,
    setAshlarThickness,
    ashlarAutoCommitOnMouseUp,
    setAshlarAutoCommitOnMouseUp,
    floraPreset,
    setFloraPreset,
    floraAutoCommitOnMouseUp,
    setFloraAutoCommitOnMouseUp,
    floraHeight,
    setFloraHeight,
    floraGirth,
    setFloraGirth,
    floraWobble,
    setFloraWobble,
    floraTaper,
    setFloraTaper,
    floraStemCount,
    setFloraStemCount,
    floraClusterRadius,
    setFloraClusterRadius,
    floraBranchCount,
    setFloraBranchCount,
    floraBranchDepth,
    setFloraBranchDepth,
    floraBranchStart,
    setFloraBranchStart,
    floraBranchSpread,
    setFloraBranchSpread,
    floraBraidStrands,
    setFloraBraidStrands,
    floraBraidTwist,
    setFloraBraidTwist,
    floraCanopy,
    setFloraCanopy,
    roofAreaShape,
    setRoofAreaShape,
    roofPins,
    setRoofPins,
    roofPinsRef,
    roofFirstClickRef,
    setRoofFirstClick,
    roofStyle,
    setRoofStyle,
    roofHeight,
    setRoofHeight,
    roofHollow,
    setRoofHollow,
    shapeKind,
    setShapeKind,
    shapeSize,
    setShapeSize,
    shapeOverwrite,
    setShapeOverwrite,
  };

  return {
    generatorKind,
    setGeneratorKind,
    generatorKindRef,
    generatorSphereRadius,
    setGeneratorSphereRadius,
    generatorSphereRadiusRef,
    generatorToolOptionsModel,
    rocksAutoCommitOnMouseUp,
    setRocksAutoCommitOnMouseUp,
    rocksAutoCommitOnMouseUpRef,
    rockRoughness,
    setRockRoughness,
    rockRoughnessRef,
    rockCount,
    setRockCount,
    rockCountRef,
    rockClusterRadius,
    setRockClusterRadius,
    rockClusterRadiusRef,
    rockSinkDirection,
    setRockSinkDirection,
    rockSinkDirectionRef,
    rockSinkAmount,
    setRockSinkAmount,
    rockSinkAmountRef,
    rockPreviewSeedRef,
    placeRocksAtScreen,
    rocksPhase,
    grassAutoCommitOnMouseUp,
    setGrassAutoCommitOnMouseUp,
    grassAutoCommitOnMouseUpRef,
    grassDensity,
    setGrassDensity,
    grassDensityRef,
    grassMaxHeight,
    setGrassMaxHeight,
    grassMaxHeightRef,
    grassPreviewSeedRef,
    placeGrassAtScreen,
    grassPhase,
    ashlarAutoCommitOnMouseUp,
    setAshlarAutoCommitOnMouseUp,
    ashlarAutoCommitOnMouseUpRef,
    ashlarThickness,
    setAshlarThickness,
    ashlarThicknessRef,
    ashlarPreviewSeedRef,
    placeAshlarAtScreen,
    ashlarPhase,
    floraAutoCommitOnMouseUp,
    setFloraAutoCommitOnMouseUp,
    floraAutoCommitOnMouseUpRef,
    floraPreset,
    setFloraPreset,
    floraHeight,
    setFloraHeight,
    floraGirth,
    setFloraGirth,
    floraWobble,
    setFloraWobble,
    floraTaper,
    setFloraTaper,
    floraStemCount,
    setFloraStemCount,
    floraClusterRadius,
    setFloraClusterRadius,
    floraBranchCount,
    setFloraBranchCount,
    floraBranchDepth,
    setFloraBranchDepth,
    floraBranchStart,
    setFloraBranchStart,
    floraBranchSpread,
    setFloraBranchSpread,
    floraBraidStrands,
    setFloraBraidStrands,
    floraBraidTwist,
    setFloraBraidTwist,
    floraCanopy,
    setFloraCanopy,
    floraPreviewSeedRef,
    placeFloraAtScreen,
    floraPhase,
    clothGravityDirection,
    setClothGravityDirection,
    clothGravityDirectionRef,
    ropeBrushRadiusIndex,
    setRopeBrushRadiusIndex,
    ropeBrushRadiusIndexRef,
    ropeBrushShapeUi,
    setRopeBrushShapeUi,
    ropeBrushShapeUiRef,
    ropeFirstScreen,
    setRopeFirstScreen,
    setRopeFirstVoxel,
    ropeFirstVoxelRef,
    ropeSag,
    ropeTension,
    setRopeTension,
    ropeTensionRef,
    ropePhase,
    clothPins,
    setClothPins,
    clothPinsRef,
    clothTension,
    setClothTension,
    clothTensionRef,
    clothSimGravityPct,
    setClothSimGravityPct,
    clothSimGravityPctRef,
    clothSimStiffnessPct,
    setClothSimStiffnessPct,
    clothSimStiffnessPctRef,
    clothSimIterations,
    setClothSimIterations,
    clothSimIterationsRef,
    clothSimConstraintPasses,
    setClothSimConstraintPasses,
    clothSimConstraintPassesRef,
    clothPhase,
    handleClothPinClick,
    roofStyle,
    setRoofStyle,
    roofStyleRef,
    roofHeight,
    setRoofHeight,
    roofHeightRef,
    roofHollow,
    setRoofHollow,
    roofHollowRef,
    roofPins,
    setRoofPins,
    roofPinsRef,
    roofAreaShape,
    setRoofAreaShape,
    roofAreaShapeRef,
    roofFirstClick,
    setRoofFirstClick,
    roofFirstClickRef,
    shapeKind,
    setShapeKind,
    shapeKindRef,
    shapeSize,
    setShapeSize,
    shapeSizeRef,
    shapeRotX,
    setShapeRotX,
    shapeRotXRef,
    shapeRotY,
    setShapeRotY,
    shapeRotYRef,
    shapeRotZ,
    setShapeRotZ,
    shapeRotZRef,
    shapeOverwrite,
    setShapeOverwrite,
    shapeOverwriteRef,
    shapePhase,
    shapeGizmoPosRef,
  };
}
